sudo: required
language: python
python:
    - "3.6"

addons:
  firefox: latest

before_install:
    - pip install pep8
    - sudo chmod +x install_driver.sh
    - ./install_driver.sh

install:
    - pip install -r requirements.txt

script:
    - find . -name '*\*.py' -exec pep8 {} +

notifications:
    email: false
